name: Post release

on:
  release:
    types: [published]

jobs:
  post_release:
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Update website
        run: |
          curl --fail-with-body -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.WEBSITE_REPO_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/scb261/website/dispatches \
          -d '{"event_type":"app_release"}'
